server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    org:
      zalando:
        logbook: trace
logbook:
  filter:
    form-request-mode: off
  format:
    style: http
chatgpt:
  api-key: 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
# some properties as below have default values. For descriptions of these fields, please refer to https://platform.openai.com/docs/api-reference/completions/create and https://platform.openai.com/docs/api-reference/chat/create
  url: https://api.openai.com/v1/completions
  model: text-davinci-003
  max-tokens: 500
  temperature: 1.0
  top-p: 1.0
  multi:
     url: https://api.openai.com/v1/chat/completions
     model: gpt-3.5-turbo
     max-tokens: 500
     temperature: 1.0
     top-p: 1.0
   image:
     url: https://api.openai.com/v1/images/generations
